#!/bin/sh

#compile latex

if [ $# -eq 0 ]; then
    echo "Please provide project tex file and .bib"
    exit 1
fi

pdflatex $1.tex && bibtex $1 && pdflatex $1.tex && bibtex $1 && pdflatex $1.tex && pdflatex $1.tex
